fieldLayouts:
  50a9dc97-c214-46f1-a6eb-6059f982357c:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 04ab3c60-f325-48ea-bf96-347befb870e0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 64e51b90-5f2d-49a4-8a17-c6a5ff230049
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: cc7a7777-17c5-45ef-829d-9b277cb85134
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d7b767e3-b7c2-4a02-a2c2-556c9c92ff1b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b590bffb-b895-4106-ad8a-5aef5a0624aa
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 30f03610-28d7-4b19-a068-e7a8273b06f2
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d6cfd573-00b8-4ab5-b8d9-4950413ca9e0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: cf6bcfb0-3ed0-43f3-85af-cda938cd8466
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4cbb40f3-b363-4b4c-8b09-128450335cf1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2ad113e3-a68b-4fc9-8d9c-ac2f8186714f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f7797baf-be7c-4100-86e8-d372cb882518
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Projects
        sortOrder: 1
      -
        elements:
          -
            fieldUid: dfb201c1-5d86-40c2-8ef8-8a447a607828
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fe83906d-6f96-4f77-9151-41326628a78d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: projects
hasTitleField: true
name: Projects
section: 32174234-e8c3-40d4-9725-77ff2bd2366a
sortOrder: 1
titleFormat: ''
