contentColumnType: text
fieldGroup: 4af81e2f-0766-4fd9-aa87-7ae1ccb1cffd
handle: copyright
instructions: ''
name: Copyright
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
